### ISSUE TITLE
upstreams 下的 dial_addr 选项是否可以添加配置 多 IP，并且连接上游 DOH 服务器时随机选择 IP 连接的 特性？

### ISSUE THREAD

**Issue by jzp820927** [IrineSistiana/mosproxy#4]
upstreams 配置的上游服务器在使用 DOH 的时候，dial_addr 是否可以添加配置 多个 IP，并且每次连接 DOH 上游服务器的时候，都随机选择 IP 连接的功能？另外还有就是在 IP 连接失败的时候，可以继续随机选择另一个 IP 进行连接的功能？避免单个 IP ，或者长期连接单个 IP，出现单点故障的问题。大佬可以添加这2个功能特性麽？

**Comment by IrineSistiana** [comment]
typo

**Comment by IrineSistiana** [comment]
已实现负载均衡
