### ISSUE TITLE
UDP 协议监听链路地址 (FE80) sendmmsg: invalid argument

### ISSUE THREAD

**Issue by klxyy** [IrineSistiana/mosproxy#8]
使用内网链路地址（FE80）解析时报错：
failed to write batch msg error="write udp [::]:53: sendmmsg: invalid argument" module=server_udp
使用TCP协议时能正常解析。

**Comment by IrineSistiana** [comment]
无法理解你的表述。无法复现问题。请提供详细信息，使用场景。

**Comment by klxyy** [comment]
> 无法理解你的表述。无法复现问题。请提供详细信息，使用场景。

![mosProxy](https://github.com/user-attachments/assets/9fbd35c8-e076-42ef-abcf-09eecf0af284)

详情见图，fe80::11为本机本地链路地址，240e为本机公网地址。
配置文件：
servers:
  - protocol: "udp"
    listen: "0.0.0.0:53"
    idle_timeout: 0
    udp:
      multi_routes: true
    
  - protocol: "tcp"
    listen: "0.0.0.0:53"
    idle_timeout: 0
    tcp:
      max_concurrent_queries: 1000

**Comment by IrineSistiana** [comment]
UDP 往 fe80 发送数据包要绑定接口

你设置 so_bindtodevice 试试

**Comment by klxyy** [comment]
> UDP 往 fe80 发送数据包要绑定接口
> 
> 你设置 so_bindtodevice 试试

感谢大佬，问题解决
